### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by viniciusnavarro** [wurstbrot/DevSecOps-MaturityModel#158]
Hello everyone, after following the recommendations, when running the docker command I got this error:

`realpath: /bitnami/nginx/conf/vhosts: No such file or directory`

Am I missing some part of the configuration?

**Comment by wurstbrot** [comment]
Hi @viniciusnavarro , which commands did you run?

**Comment by viniciusnavarro** [comment]
Hello @wurstbrot 

The command is this: `docker run --rm -p 8084:80 wurstbrot/dsomm:latest`

![img](https://user-images.githubusercontent.com/41381141/191814788-f8345544-692b-4433-8fe4-49c8de1fb48e.png)

and it gets stuck on Starting Nginx.

**Comment by wurstbrot** [comment]
Hi @viniciusnavarro ,

this is just an info. It works. Please use 
` docker run --rm -p 8084:8080 wurstbrot/dsomm:latest`.

**Comment by viniciusnavarro** [comment]
It worked, I was mapping to port 80 instead of mapping to 8080, thanks for the help @wurstbrot
