### ISSUE TITLE
.MD parser for additional text

### ISSUE THREAD

**Issue by louwersj** [wurstbrot/DevSecOps-MaturityModel#16]
I am, as discussed, writing some more text on mapping gartner to our model and I will upload it somewhere this week. Question that comes to mind, to render additional information, would it be handy to have a markdown parser in PHP so we can introduce new pages quickly by referring to it an parsing them with a generic .md parser?

**Comment by wurstbrot** [comment]
Please add an md file too the root path and modify navi.php like in 
https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/17/

In case you plan to add multiple md files, please let me know so we include md files from a sub directory.

Can we close this issue?

**Comment by louwersj** [comment]
To keep things a bit clean and tidy I will create a sub directory. Even in case I just have one file, we might want to add more later...... I think it would be good to ensure we have one place to store the rather than having them in the root dir.

Guess we have a way forward, so I will close down this issue.
