### ISSUE TITLE
startDocker.bash missing / docker not working

### ISSUE THREAD

**Issue by 8L4ckc0FF33** [wurstbrot/DevSecOps-MaturityModel#167]
hi there, i was just trying to get dsomm to work but didn't succeed. since the current release 2.6 misses "startDocker.bash" i tried the 2.5 version as well as the direct docker version:
`docker run --rm -p 8080:8080 wurstbrot/dsomm:latest`
but unfortunately both did not work.

the first issue was  this message:
`[Thu Oct 13 21:58:54.196572 2022] [core:crit] [pid 21] (13)Permission denied: [client 172.17.0.1:44268] AH00529: /var/www/html/assets/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/html/assets/' is executable, referer: http://localhost:81/`
but i got rid of it by executing a shell on the docker container and changing the folder permissions to 755.
now i don't get any bad logs but i still get
`Warning: require_once(data/generateDimensions.php): Failed to open stream: Permission denied in /var/www/html/functions.php on line 16Fatal error: Uncaught Error: Failed opening required 'data/generateDimensions.php' (include_path='.:/usr/local/lib/php') in /var/www/html/functions.php:16 Stack trace: #0 /var/www/html/data.php(20): require_once() #1 /var/www/html/index.php(14): include_once('/var/www/html/d...') #2 {main} thrown in /var/www/html/functions.php on line 16
`
when connecting to localhost:81. what could be possibly wrong?
besides, is there any way to use DSOMM without docker? running it within a LAMP stack or similar?

**Comment by wurstbrot** [comment]
Hi @8L4ckc0FF33 ,

to me it looks like, you are using an old image. Please pull the latest version.
`docker pull  wurstbrot/dsomm:latest`

It is possible to run it locally by using:
`
ng serve
`

**Comment by wurstbrot** [comment]
as discussed in slack, it worked with a fix docker tag
