### ISSUE TITLE
Suggesting to update titles

### ISSUE THREAD

**Issue by hemedga** [wurstbrot/DevSecOps-MaturityModel#18]
Hi,
I think we should update the level titles for better communication that it actually measures performance based on an assessment of actual practices. We don't measure the understanding but rather the implemented processes and tools.

Level 1: Basic understanding of security practices
Level 2: Adoption of basic security practices
Level 3: High adoption of security practices
Level 4: Advanced deployment of security practices at scale

https://github.com/wurstbrot/DevSecOps-MaturityModel/blob/9f09c2833a4fcb3761500fcd183ccdb65a937ef9/head.php#L66-L69

**Comment by wurstbrot** [comment]
Intention: The organization has a [...] understanding of security.
The model is not having "evidence" to perform a good assessments (so every one will have different evidence). Hower, adaption is fine for me and I changed it accordingly.
