### ISSUE TITLE
Adding of activity tags

### ISSUE THREAD

**Issue by wurstbrot** [wurstbrot/DevSecOps-MaturityModel#212]
Tags like "automatable" or "vulnerability-assessment" are not visible.

As a user, I want to filter for activity tags (like for dimensions) to get a cross-dimension view of activities with the same focus.

**Comment by shubhangi013** [comment]
> Tags like "automatable" or "vulnerability-assessment" are not visible.
> 
> As a user, I want to filter for activity tags (like for dimensions) to get a cross-dimension view of activities with the same focus.

Please assign me the issue. I'd like to work on it.

**Comment by shubhangi013** [comment]
Hey ! sorry for replying late. got caught up in college :) so do you want the tags to appear while filtering just like they do in mapping ?
![Screenshot from 2023-03-11 19-27-48](https://user-images.githubusercontent.com/78342516/224488819-b65eaf07-cd25-458b-ac70-cf10c214c7a5.png)

**Comment by wurstbrot** [comment]
Hi @shubhangi013 ,

in order to perform this task, the activities in [generated.yaml](https://github.com/wurstbrot/DevSecOps-MaturityModel/blob/master/src/assets/YAML/generated/generated.yaml) needs a tag (for local testing you can just add tags in there).
Afterwards, we show the tag in the activity details:
![image](https://user-images.githubusercontent.com/955192/224531262-8d5742c3-fb29-49a0-b4d4-0a5bc95439ad.png)
In addition, we need a filter in the Matrix view for these tags.

**Comment by 0x41head** [comment]
Hi @shubhangi013 ,
I think the filter applied in matrix (the one with the chips) would be better in this case.

**Comment by akhileshappala** [comment]
Hi @wurstbrot ,
we need to get the tags attached to the activity as the filter options? is this the requirement?

**Comment by wurstbrot** [comment]
Hi @akhileshappala ,

the tags should be added to the activity. The filter option should be in the matrix view.

**Comment by ptechofficial** [comment]
Hi @wurstbrot,
In matrix view, Creating another filter in matrix view can work, like this:
![image](https://user-images.githubusercontent.com/64535754/229900446-48e58918-0117-4f02-a1d5-fd74722d2938.png)

**Comment by wurstbrot** [comment]
implemented
