### ISSUE TITLE
Move to Hugo/yml?

### ISSUE THREAD

**Issue by wurstbrot** [wurstbrot/DevSecOps-MaturityModel#7]
OWASP SAMM is using hugo based creation of website (https://owaspsamm.org/blog/2020/03/31/samm-is-doing-cicd/).

Pro:
- Only static files are served in the first step. In the long run, the spider web diagram with the interaction of selecting what has been finished might be integrated.

Con:
- Work, content updates will be delayed

@louwersj @clazba : What are your opinions? Should I focus on enhancing the content or the interface?

**Comment by louwersj** [comment]
Personally I think content is king... meaning... focus should be on content first. Happy to support on the creation of some new content by the way. 

Just my 2 cents on this topic :-)

**Comment by clazba** [comment]
Not seen the site in a while but I guess it depends on whether you feel the
interface is currently good enough for people to consume your content.
Otherwise, regardless of the quality of your content, if it's difficult to
consume or find more content won't help.
On the other hand, if the interface is "good enough" I'd go for content.

**Comment by louwersj** [comment]
As @clazba stated "good enough". I think for now the look and feel is good enough.. yes it could improve, however... for this topic the content matters more and is the real value. Even though having a better interface helps in finding information the information is the thing people are looking for. 

Guess we could focus on adding valuable content. That would lead to the following question... what do you think needs to be added on a priority from a content point of view. 

Johan.

**Comment by wurstbrot** [comment]
I close this issue due to the agreement to focus on content. I created some issue with ideas what to improve next.
