### ISSUE TITLE
Report Generation is not working

### ISSUE THREAD

**Issue by Jayp0weru5r** [wurstbrot/DevSecOps-MaturityModel#89]
After completing and checking off several items on "implementation level" when going to generate a report it is not working. The following error is observed.

```php
Warning: Undefined variable $tableContent in /var/www/html/report.php on line 57

Fatal error: Uncaught ArgumentCountError: Too few arguments to function elementIsSelected(), 1 passed in /var/www/html/report.php on line 59 and exactly 2 expected in /var/www/html/bib.php:76 Stack trace: #0 /var/www/html/report.php(59): elementIsSelected('Building and te...') #1 {main} thrown in /var/www/html/bib.php on line
```

Do I need to add or update any content to get this working? I looked through the php file referenced, but I am not able to identify what is causing the problem. 

Please let me know if any further details are needed. 

Appreciate your time and you sharing this with the community.

**Comment by wurstbrot** [comment]
thanks @Jayp0weru5r , it is fixed.
