### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by louwersj** [wurstbrot/DevSecOps-MaturityModel#9]
Looks like the rending of the matrix is not happing in the right manner... I will have a look at it later today / this weekend. However, maybe someone can already have a look. Guess an issue with one of the yml files.

**Comment by wurstbrot** [comment]
https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/10

**Comment by louwersj** [comment]
Guess we are still missing some parts... or I might miss the point... I see;

"Build and Deployment". -- BuildandDeployment.yml
"Build and Deployment" -- TestandVerification.yml
"Information Gathering"  -- Informationgathering.yml
"Patch Management". -- PatchManagement.yml

Looks like I am missing the content from: 
CultureandOrg.yml
Infrastructure.yml

**Comment by wurstbrot** [comment]
Hi @louwersj,

from my point of view it is fixed. There is no pipeline directly performing a deployment. I deployed to dsomm.timo-pagel.de.
Do you still see the issue?

Cheers,
Timo

**Comment by louwersj** [comment]
Looks like this one is solved. We can close this one.
